gText_Birch_Welcome:: @ 82C897B
	.string "Ciao! Scusami per averti fatto,\n"
	.string "aspettare! Ti do il benvenuto nel\l"
	.string "mondo dei Pokémon! Il mio nome è\l"
	.string "SHERMAN! Eppure, tutti mi chiamano\l"
	.string "Professore Pokémon o Prof.Sherman!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Questo è un “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Questo mondo è abitato da\n"
	.string "creature chiamate POKéMON.\p"
	.string "Noi umani viviamo con i POKéMON,\n"
	.string "a volte come amici e altre\l"
	.string "volte come compagni di squadra.\p"
	.string "Spesso capita di cooperare\n"
	.string "e sfidare altri come noi.\p"
	.string "Ma nonostante questo, però,\n"
	.string "non sappiamo tutto sui POKéMON.\p"
	.string "Infatti, ci sono moltissimi\n"
	.string "segreti riguardanti i POKéMON.\p"
	.string "Per scoprire questi misteri,\n"
	.string "Ho iniziato le mie ricerche.\l"
	.string "Questo è il mio lavoro.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Parlami un pò di te!$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Sei un ragazzo?\n"
	.string "O una ragazza?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Capisco.\n"
	.string "Come ti chiami?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Così sei {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "Tu sei {PLAYER}{KUN}.\n"
	.string "Mi è tutto chiaro adesso!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Va bene, sei pronto?\p"
	.string "La tua avventura sta per\n"
	.string "iniziare.\p"
	.string "Abbi coraggio e tuffati nel\n"
	.string "mondo dei POKéMON dove sogni,\l"
	.string "avventure, e amicizie ti aspettano!\p"
	.string "Bene, buona fortuna!\n"
	.string "{PLAYER}{KUN}.\p"
	.string "$"
