gText_ObtainedTheItem:: @ 8272A78
	.string "Ha ottenuto {STR_VAR_2}!$"

gText_TheBagIsFull:: @ 8272A89
	.string "La Borsa è piena…$"

gText_PutItemInPocket:: @ 8272A9A
	.string "{PLAYER} ha messo {STR_VAR_2}\n"
	.string "nella tasca {STR_VAR_3}.$"

gText_PlayerFoundOneItem:: @ 8272ABF
	.string "{PLAYER} ha trovato {STR_VAR_2}!$"

gText_TooBadBagIsFull:: @ 8272AD0
	.string "Peccato!\n"
	.string "La Borsa è piena…$"

gText_PlayerPutItemInBag:: @ 8272AEA
	.string "{PLAYER} ha messo {STR_VAR_2}\n"
	.string "nella Borsa.$"

gText_ObtainedTheDecor:: @ 8272B09
	.string "Ha ottenuto {STR_VAR_2}!$"

gText_NoRoomLeftForAnother:: @ 8272B1A
	.string "Peccato! Non c'è più spazio\n"
	.string "per un'altra {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC:: @ 8272B48
	.string "{STR_VAR_2} è trasferita\n"
	.string "nel PC.$"
