Text_BootUpPC: @ 827265A
	.string "{PLAYER} ha acceso il PC.$"

gText_WhichPCShouldBeAccessed:: @ 827266F
	.string "A quale PC vorresti accedere?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "Accesso al PC di ???$"

gText_StorageSystemOpened:: @ 82726A3
	.string "Sistema POKéMON aperto.$"

gText_AccessedPlayersPC:: @ 82726C2
	.string "Accesso al PC di {PLAYER}.$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "Accesso al PC di Lanette.$"
