gText_PkmnTransferredSomeonesPC:: @ 8273216
	.string "{STR_VAR_2} trasferito nel\n"
	.string "PC di Qualcuno.\p"
	.string "Posizionato dentro il\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC:: @ 8273256
	.string "{STR_VAR_2} trasferito to\nLANETTE'S PC.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull:: @ 8273296
	.string "BOX “{STR_VAR_3}” attivo\n"
	.string "Pc di Qualcuno è pieno.\p"
	.string "{STR_VAR_2} trasferito nel\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull:: @ 82732D9
	.string "BOX “{STR_VAR_3}” on\n"
	.string "LANETTE'S PC was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon:: @ 827331C
	.string "Non c'è spazio per altri Pokémon!!\p"
	.string "I Box POKéMON sono pieni e\n"
	.string "non possono ospitarne altri!$"

gText_NicknameThisPokemon:: @ 8273374
	.string "Vuoi dare un soprannome a\n"
	.string "questo {STR_VAR_1}?$"
