gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
    .string "Ciao, ti do il benvenuto\n"
    .string "al Centro Pokémon.\p"
    .string "Riportiamo i tuoi pokémon\n"
    .string "al pieno delle loro forze.\p"
    .string "Vorresti far riposare i tuoi Pokémon?$"

gText_IllTakeYourPkmn:: @ 8272768
    .string "Va bene, prenderò i tuoi Pokémon\n"
    .string "per qualche secondo.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
    .string "Grazie per l'attesa.\p"
    .string "I tuoi Pokémon sono in\n"
    .string "perfetta salute.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "Siamo sempre a disposizione!$"

gText_WelcomeCutShort:: @ 82727F5
    .string "Ciao, benvenuto\n"
    .string "al Centro Pokémon.\p"
    .string "Riportiamo i tuoi pokémon\n"
    .string "al pieno delle loro forze.\p"
    .string "Vorresti far riposare i tuoi Pokémon?…$"

gText_NoticesGoldCard:: @ 8272860
    .string "Th-that card…\n"
    .string "Could it be… The GOLD CARD?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several TRAINERS with\n"
    .string "a SILVER CARD before, but, {PLAYER},\l"
    .string "you're the first TRAINER I've ever\l"
    .string "seen with a GOLD CARD!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual:: @ 8272982
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2:: @ 82729C0
    .string "Okay, prenderò i tuoi Pokémon\n"
    .string "per qualche secondo.$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Grazie per l'attesa.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
    .string "Siamo sempre a disposizione!$"
