	.align 2
gText_ConfirmSave:: @ 82C87B4
	.string "Vorresti salvare i tuoi progressi?$"

gText_AlreadySavedFile:: @ 82C87D5
	.string "E' già presente un salvataggio.\n"
	.string "Vorresti sovrascriverlo?$"

gText_SavingDontTurnOff:: @ 82C8810
	.string "Salvando…\n"
	.string "Attendi prima di spegnere!$"

gText_PlayerSavedGame:: @ 82C8832
	.string "{PLAYER} ha salvato il gioco.$"

gText_DifferentSaveFile:: @ 82C8845
	.string "ATTENZIONE!\p"
	.string "E' già presente un file di\n"
	.string "salvataggio.\p"
	.string "Se salvi adesso, tutti i progressi\n"
	.string "andranno perduti permanentemente.\p"
	.string "Vuoi comunque salvare adesso\n"
	.string "e sovrascrivere il salvataggio?$"

gText_SaveError:: @ 82C892A
	.string "Errore nel salvataggio.\p"
	.string "Per cortesia, cambia\n"
	.string "la memoria di backup.$"

gText_SavingDontTurnOffPower:: @ 82C8959
	.string "Salvando…\n"
	.string "Attendi prima di spegnere!$"
