OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 81FBE86
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
.string "Un tempo, vivevo a Lavandonia,\n"
.string "nel Kanto. Da quando Ancar è\l"
.string "diventata la regione primaria, mi\l"
.string "sono trasferita qui. Mi manca la\l"
.string "malinconia che si respirava lì...$"
